Transformers: main.o Arena.o Robot.o Bulldozer.o Roomba.o Humanic.o Optimusprime.o Robocop.o
	g++ -std=c++11 main.o Arena.o Robot.o Bulldozer.o Roomba.o Humanic.o Optimusprime.o Robocop.o -o Transformers
	rm *.o

main.o: main.cpp 
	g++ -std=c++11 -c main.cpp

Arena.o: Arena.cpp 
	g++ -std=c++11 -c Arena.cpp

Robot.o: Robot.cpp 
	g++ -std=c++11 -c Robot.cpp

Bulldozer.o: Bulldozer.cpp 
	g++ -std=c++11 -c Bulldozer.cpp

Roomba.o: Roomba.cpp 
	g++ -std=c++11 -c Roomba.cpp

Humanic.o: Humanic.cpp
	g++ -std=c++11 -c Humanic.cpp

Optimusprime.o: Optimusprime.cpp
	g++ -std=c++11 -c Optimusprime.cpp

Robocop.o: Robocop.cpp
	g++ -std=c++11 -c Robocop.cpp

clean:
	rm *.o

